### ISSUE TITLE
Tela de Login

### ISSUE THREAD

**Issue by JonathanAlcantara** [ESEGroup/IssuesAuthenticatorJararacucu#12]
Quais são os dados para acesso? Acho que as opções de login, recuperar senha e "pular" (que não sei o que significa) não estão funcionando.

**Comment by raphaelfilene** [comment]
O login, para funcionar, precisa ter quase todo o back-end funcionando, ou seja, precisamos antes mexer com o Issues Monitoring, criar um banco de dados e um sistema de autenticação dentro do mesmo. Além disso, pretendemos restringir as demais telas para o acesso apenas de usuários logados e por isso criei o link “pular”, pois ele nos possibilitaria ver as telas pós-login, até que todo o back-end necessário esteja pronto e então seja retirado tal link.


Em 23 de nov de 2017, à(s) 16:58, Jonathan Alcantara <notifications@github.com<mailto:notifications@github.com>> escreveu:


Quais são os dados para acesso? Acho que as opções de login, recuperar senha e "pular" (que não sei o que significa) não estão funcionando.
