### ISSUE TITLE
Informar com urgencia onde o Issues Monitoring deste projeto pode ser acessado

### ISSUE THREAD

**Issue by ghtravassos** [ESEGroup/IssuesAuthenticatorJararacucu#18]
Qual o endereço do servidor Issues Monitoring que esta disponivel para o Issues Authenticator? Os testes dependem disso.

**Comment by klausnq** [comment]
Para realizarmos os testes de serviços precisamos da URL disponível para acesso com credenciais para login, bem como a documentação referente aos serviços REST  implementados.

**Comment by GabrielAzeredo** [comment]
O IssuesMonitoring está rodando no 35.199.79.158:8081

**Comment by victor0machado** [comment]
Login e senha: admin/admin
