### ISSUE TITLE
Correção de salas e rever divisão na aba de configurações

### ISSUE THREAD

**Issue by JonathanAlcantara** [ESEGroup/IssuesAuthenticatorJararacucu#9]
Achei estranho a divisão entre salas (o nome "H-318" está errado, é "H-317") e laboratórios. Acho desnecessária essa subdivisão, mas gostei da página exclusiva para indicar quais salas estão devidamente salvas.

Comentário do Victor.

**Comment by jvdavim** [comment]
A divisão por salas está relacionada ao Wifi de cada uma. O MAC address poderá ser reconfigurado posteriormente para garantir a manutebilidade. Será feita a correção para a sala H-317 e fechada a issue.
